-- ==========================================
-- 1. SETUP TABEL PENGHUNI (OCCUPANTS)
-- ==========================================
CREATE TABLE occupants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id BIGINT REFERENCES rooms(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  phone TEXT,
  ktp_image TEXT,
  move_in_date DATE NOT NULL DEFAULT CURRENT_DATE,
  status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

ALTER TABLE occupants ENABLE ROW LEVEL SECURITY;

-- Hanya admin yang bisa akses data penghuni
CREATE POLICY "Admins can manage occupants" 
  ON occupants FOR ALL 
  USING (auth.uid() IS NOT NULL);


-- ==========================================
-- 2. SETUP TABEL TRANSAKSI / KEUANGAN
-- ==========================================
CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL CHECK (type IN ('Income', 'Expense')),
  amount INTEGER NOT NULL,
  description TEXT NOT NULL,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  occupant_id BIGINT REFERENCES occupants(id) ON DELETE SET NULL, -- Nullable (bisa untuk pengeluaran yg ga terkait penghuni)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- Hanya admin yang bisa kelola keuangan
CREATE POLICY "Admins can manage transactions" 
  ON transactions FOR ALL 
  USING (auth.uid() IS NOT NULL);


-- ==========================================
-- 3. SETUP STORAGE BUCKET (GUDANG FOTO)
-- ==========================================
-- Membuat bucket baru bernama 'kostan_media'
INSERT INTO storage.buckets (id, name, public) 
VALUES ('kostan_media', 'kostan_media', true)
ON CONFLICT (id) DO NOTHING;

-- Membuat policy agar publik bisa melihat/mengunduh gambar
CREATE POLICY "Public Access" 
  ON storage.objects FOR SELECT 
  USING (bucket_id = 'kostan_media');

-- Membuat policy agar HANYA ADMIN yang bisa mengupload, update, delete gambar
CREATE POLICY "Admin Upload Access" 
  ON storage.objects FOR INSERT 
  WITH CHECK (bucket_id = 'kostan_media' AND auth.uid() IS NOT NULL);

CREATE POLICY "Admin Update Access" 
  ON storage.objects FOR UPDATE 
  USING (bucket_id = 'kostan_media' AND auth.uid() IS NOT NULL);

CREATE POLICY "Admin Delete Access" 
  ON storage.objects FOR DELETE 
  USING (bucket_id = 'kostan_media' AND auth.uid() IS NOT NULL);
