-- Buka SQL Editor di Supabase Dashboard kamu dan jalankan query ini:

-- 1. Buat tabel rooms
CREATE TABLE rooms (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'Available' CHECK (status IN ('Available', 'Occupied')),
  occupant TEXT DEFAULT '-',
  facilities TEXT[] DEFAULT '{"AC", "Wifi", "Kasur"}'::TEXT[],
  image TEXT DEFAULT 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::TEXT, NOW()) NOT NULL
);

-- 2. Setup Row Level Security (RLS)
-- Untuk MVP, kita buka akses READ untuk publik (Landing Page)
-- Tapi untuk INSERT/UPDATE/DELETE harus dikunci, namun karena kita belum setup Auth,
-- sementara kita open dulu aksesnya biar gampang testing dari Localhost.
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access"
  ON rooms FOR SELECT
  USING (true);

-- CATATAN: Untuk MVP tanpa login, kita open akses insert/update/delete.
-- Nanti kalau fitur login admin udah dibikin, policy ini WAJIB diganti!
CREATE POLICY "Allow all actions for now"
  ON rooms FOR ALL
  USING (true);

-- 3. Masukkan data dummy awal
INSERT INTO rooms (name, price, status, occupant, facilities, image) VALUES
('Kamar A-01 Deluxe', 1500000, 'Available', '-', ARRAY['AC', 'KM Dalam', 'Wifi', 'Kasur'], 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'),
('Kamar A-02 Deluxe', 1500000, 'Occupied', 'Andi Pratama', ARRAY['AC', 'KM Dalam', 'Wifi', 'Kasur'], 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=800'),
('Kamar B-01 Standard', 1200000, 'Available', '-', ARRAY['AC', 'Wifi', 'Kasur'], 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&q=80&w=800'),
('Kamar C-01 Budget', 900000, 'Occupied', 'Siti Aminah', ARRAY['Wifi', 'Kasur', 'Lemari'], 'https://images.unsplash.com/photo-1505691938895-1758d7eaa511?auto=format&fit=crop&q=80&w=800');
